name: ShaiHive
description: A secure cryptocurrency wallet with verifiable credentials support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  bs58check: ^1.0.2
  bech32: ^0.2.2
  bip39: ^1.0.6
  hex: ^0.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  model_viewer_plus: ^1.7.0
  http: ^1.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/logo.png
    - assets/images/
    - lib/bip39/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/icon.png"
  macos:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 1024
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 256
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#000000"
    theme_color: "#FFD700"
